filegroup(
    name = "textures",
    srcs = glob(["*.png"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "fonts",
    srcs = glob(["*.ttf"]),
    visibility = ["//visibility:public"],
)
